class Config:
    FRAME = None

    WIDTH = 1.0
    HEIGHT = 1.0
    
    BOARDS_NUM = 3
    BUTTONS_NUM = 4
    COMPONENTS_NUM = 6
    COMPONENTS_ON_BOARD = 3

    SELECTED_COMPONENT = None
    SELECTED_BOARD = None

    MAIN_BUTTONS_SCALE_Y = 1 / BUTTONS_NUM
    MAIN_BUTTONS_SCALE_X = MAIN_BUTTONS_SCALE_Y * 10 / 16

    STACK_W = 0.2
    STACK_H = HEIGHT
    STACK_X = MAIN_BUTTONS_SCALE_X
    STACK_Y = (HEIGHT - STACK_H) / 2

    BOARD_W = 0.5 * WIDTH
    BOARD_X = STACK_X + STACK_W + (1 - STACK_X - STACK_W - BOARD_W) / 2

    BOARDS_COLOR = (7, 166, 50)
